### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by AbdulkodirBurganov** [yarlykov/hotel_toxin#14]
1. Баг при изменении поля кол-ва какого-то конкретного типа гостей + почему-то при определенном кол-ве гостей больше не получается добавить
![Дропдаун2](https://user-images.githubusercontent.com/89448992/130693901-00993c88-917d-435b-8d20-2dbbda415770.gif)
2. Список не разворачивается
![Список](https://user-images.githubusercontent.com/89448992/130694170-ffb9109a-ec75-4615-b4fd-37b6375b53a8.gif)

**Comment by yarlykov** [comment]
По изменению поля  - инпут используется здесь только для удобства работы со значениями счетчика гостей. Моя ошибка была оставить его открытым для изменения.
Если посмотреть на макет, то судя по расположению кнопок, их размерам и расстоянию между ними возможность изменять вручную значение счетчика не подразумевалась дизайнером.
Я убрал возможность изменения, но если такой функционал необходим, то я сделаю валидацию введенных данных. 

Что касается ограничения на количество гостей, оно задается при инициализации дропдауна и было равно 20. Увеличил это значение.
![Снимок экрана 2021-08-25 в 13 11 47](https://user-images.githubusercontent.com/60186280/130736064-23bbca0d-3632-4b8b-b5b1-a3830e32f139.png)

**Comment by AbdulkodirBurganov** [comment]
1.Было бы хорошо еще сделать так, чтобы календарь так же закрывался при клике на внешнюю область, как и дропдаун.
![Календарь не закрывается](https://user-images.githubusercontent.com/89448992/131573113-f170ebdb-59fd-47bf-b18b-82674487f27a.gif)
2. При maxItems = 5 кнопка деактивируется только после повторного нажатия на +
![Деактивирование кнопки](https://user-images.githubusercontent.com/89448992/131575576-8807cea0-a179-494e-b849-df4200549b34.gif)
3. Какое-то странное поведение бургеров на странице с хедерами и бургерами.
![Какое-то странное поведение бургеров на странице с хедерами и футерами](https://user-images.githubusercontent.com/89448992/131576133-7efaece2-4546-4569-a905-5ba718afea0c.gif)
4. Выпадающее меню в хедере при маленьких размерах вылезает за окно
![выпадающее меню](https://user-images.githubusercontent.com/89448992/131578106-6f615e67-b4f6-4cca-b96f-562b40159be9.gif)
