### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by kate-fsd** [yarlykov/hotel_toxin#27]
В button можно значительно сократить код
![image](https://user-images.githubusercontent.com/66846004/140987715-3c831d8c-fea9-4251-a736-fbf34e06da44.png)

И можно название тега вынести в переменную, а buttonAttributes.link изменить на a

**Comment by kate-fsd** [comment]
Файл содержащий класс принято назвать с заглавной буквы

**Comment by kate-fsd** [comment]
а почему не просто js-className?
![image](https://user-images.githubusercontent.com/66846004/140996108-98fd8ed6-71e5-4519-ab31-cededec6b63b.png)

**Comment by yarlykov** [comment]
не стал полностью убирать дата-атрибуты, потому что в некоторых местах их использование действительно оправдано

**Comment by kate-fsd** [comment]
Я не против data-атрибутов в тех местах где они нужны, но для поиска в компоненте нужно использовать класс с префиксом js-
![image](https://user-images.githubusercontent.com/66846004/142192180-955ac222-5c27-484e-bd5f-ff2e5b8c34cc.png)

**Comment by kate-fsd** [comment]
Проверку на > 0 можно и не делать) можешь не исправлять
![image](https://user-images.githubusercontent.com/66846004/142191420-6e2e8a59-f806-480d-9fa9-4c66d7148823.png)

**Comment by kate-fsd** [comment]
file date-dropdown.pug строка 4. Такие длинные строки разбивай на несколько, чтобы текст уместился на экране

**Comment by kate-fsd** [comment]
JSON.parse желательно оборачивать в try catch, но можешь не справлять пока

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142198235-045c88e7-be1b-4200-b5fe-648a714fdfac.png)
В disabled лучше передавать true/false. А классы совсем убрать

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142202847-9f29c36e-1425-4f02-8066-c809d935f227.png)
1. Обращение к внешнему блоку
2. Класс без js-

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142203350-d107aa38-a70b-43d5-8665-3b24199582c1.png)
Класс должен быть то же что и компонент и папка

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142203916-53d4ffe1-3ad9-476a-a768-338bb3c40233.png)
Не нужно дублировать disabled для элемента

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142204434-c74ccc5f-7517-457e-ba2a-870970fb054e.png)
Тут напрашивается булевый модификатор

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142204634-1841f45c-f70b-4d5e-8e3e-a7e4d4b9c6e1.png)
От методов можно избавиться, они совсем простые) По желанию

Старайся всегда использовать безопасную вставку через textContent

**Comment by kate-fsd** [comment]
Проверь menu-widget на ошибки

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142207110-fcb063c0-1613-4e5d-83cd-8a1e6004eae2.png)
Это динамические данные, они не должны лежать в компоненте

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142208096-58f4b0f7-f716-45f5-a1c2-fe2346fa3cbe.png)
Неправильная логика. На первой странице айтемы с 1 по 12 . На второй - с 13 по 24 ...

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142208717-a57984f4-e5a9-4363-8539-f8314312e1ef.png)
Тут дефолтное значение для size - недопустимо, получим плохой класс. И некоторые другие дефолты тоже. Проверь, есть ли еще где то подобное

Еще если вставляешь напрямую в название класса, проверяй, что параметр удовлетворяет условиям, например:
["small", "middle", "large"].includes(size)

**Comment by kate-fsd** [comment]
остался неиспользуемый
![image](https://user-images.githubusercontent.com/66846004/143890674-f60724eb-85ad-4c92-8639-6c5e1f63c8db.png)


![image](https://user-images.githubusercontent.com/66846004/143890753-026eaa5b-e7c6-4ad9-bc59-c2834d41ddae.png)
Если элементы не найдены вернется пустая коллекция, так что проверка не нужна


dropdown__button-clear_show
Модификатор не прилагательное 


> ![image](https://user-images.githubusercontent.com/66846004/142202847-9f29c36e-1425-4f02-8066-c809d935f227.png)
> 
> 1. Обращение к внешнему блоку
> 2. Поиск по классу без js-

Первый пункт остался

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/143893721-1b516c20-49dd-4b20-a882-8ee8ddd53bb3.png)

Лучше это сделать одним модификатором на блоке - like checked/не checked. Потому что два модификатора на скрине взаимосвязаны, не может быть лайк неактивным, а текст активным

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/143910425-769b51d3-14e4-4182-973e-74c828870f53.png)
Дублирование данных, ниже в том же файле тоже

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/143911967-f87f8662-9a3b-443d-8b04-b37f5bacc7d0.png)
В случае ошибки нужно присвоить this.options какое то пустое валидное значение, потому что он останется undefined и ошибка может появиться в init. Либо не вызывать init вообще

**Comment by kate-fsd** [comment]
в Like есть методы buttonToggle, disabled, counter
Название функция почти всегда должно начинаться с глагола

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/144089293-fe3ebf48-6c1d-4142-a4d9-2025959937a5.png)
Вариантов может быть любое количество

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/144089617-c415704b-9a90-494c-be4c-8a1e970862b7.png)
И тут стоит добавить дефолтные значения

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/144090355-629c1f36-c08b-418e-b823-83aee3397b72.png)
Класс нужно создать для корневого элемента, а в нем найти scale
