### ISSUE TITLE
Классы

### ISSUE THREAD

**Issue by kate-fsd** [yarlykov/hotel_toxin#29]
![image](https://user-images.githubusercontent.com/66846004/140993345-ae02f293-7f74-4d2c-907c-09bd9ce11b67.png)

Идея классов в обеспечении независимости каждого отдельного экземпляра компонента, карусели в данном случае (например одна с точками, другая без). В таком классе смысла нет) Можно было обойтись одной строчкой $(.js-carousel).carousel().

**Comment by kate-fsd** [comment]
Тут похоже
![image](https://user-images.githubusercontent.com/66846004/140994508-e3407f26-ede8-426a-aa9f-e605ab3d9004.png)
На странице у тебя будет только один рабочий пончик. А если понадобится еще один?

**Comment by yarlykov** [comment]
> ![image](https://user-images.githubusercontent.com/66846004/140993345-ae02f293-7f74-4d2c-907c-09bd9ce11b67.png)
> 
> Идея классов в обеспечении независимости каждого отдельного экземпляра компонента, карусели в данном случае (например одна с точками, другая без). В таком классе смысла нет) Можно было обойтись одной строчкой $(.js-carousel).carousel().



Изначально так и было, но после предварительного ревью переписал все на классы, даже там, где они не нужны, теперь переделывать обратно?)   
![Снимок экрана 2021-11-10 в 12 34 51](https://user-images.githubusercontent.com/60186280/141057526-085bcec1-9e55-4e06-a5a6-92b44fffeaba.png)

**Comment by yarlykov** [comment]
> Тут похоже ![image](https://user-images.githubusercontent.com/66846004/140994508-e3407f26-ede8-426a-aa9f-e605ab3d9004.png) На странице у тебя будет только один рабочий пончик. А если понадобится еще один?

Поменяю `data-id`, просто это уже будет не просто chart, а у него будет осмысленное и уникальное имя)    
Либо тут я не понял в чем проблема.

**Comment by kate-fsd** [comment]
> Идея классов в обеспечении независимости каждого отдельного экземпляра компонента, карусели в данном случае (например одна с точками, другая без). В таком классе смысла нет) Можно было обойтись одной строчкой $(.js-carousel).carousel().

Немного не так) Я говорила не о том что нужно совсем убрать класс, его как раз нужно оставить. Но создавать экземпляр для каждой отдельной карусели. 
А оставить класс нужно для соблюдения одинаковой структуры в компонентах и для соблюдения стандарта)
