### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by kate-fsd** [yarlykov/hotel_toxin#31]
![image](https://user-images.githubusercontent.com/66846004/142188894-a922d7f6-a541-4c5d-b8e4-fa1e091f535d.png)

1. У тебя остался старый неиспользуемый код
2. Так делать нельзя. Ты не можешь из одного компонента/страницы влиять на стили другого https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.4 
Для этого нужно создать обертку и задавать внешнее позиционирование ей https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.6
Если где то встречается эта ошибка, исправь пожалуйста

**Comment by kate-fsd** [comment]
стили на тэге
![image](https://user-images.githubusercontent.com/66846004/142190911-1a6670e6-723f-4257-ab2a-b6619e5316e6.png)

**Comment by 888mark** [comment]
怎么学css

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/142205161-09175acd-aab5-4165-877f-cf7769895f04.png)

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/143901806-a1c1c7d8-627b-46ab-8881-7f891941d0aa.png)

Padding нужно использовать для внутреннего отступа, например в карточке, чтобы контент не прилит к границе. Для внешнего лучше margin

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/143908640-ed727ba2-cfdc-4c72-8740-c50ae3106070.png)
Не нужно добавлять префиксы вручную, это должен делать автопрефиксер

**Comment by kate-fsd** [comment]
![image](https://user-images.githubusercontent.com/66846004/144091479-91b70f39-0af9-43a3-8fd1-fd3110e06376.png)
=== width: 260px;

Но лучше width 100%, и ограничивать максимальную и минимальную ширину по необходимости.
